DROP TABLE IF EXISTS films CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS friends_list CASCADE;

DROP TABLE IF EXISTS genre_film CASCADE;

DROP TABLE IF EXISTS films_liked_list CASCADE;

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    login varchar(25),
    email varchar(50),
    birthday date
);

CREATE TABLE IF NOT EXISTS rating_list (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name varchar(5)
);

CREATE TABLE IF NOT EXISTS genre_list (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(14)
);

CREATE TABLE films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    rating_id INTEGER REFERENCES rating_list(rating_id) ON DELETE CASCADE,
    description varchar(200),
    release_date date,
    duration integer
);

CREATE TABLE friends_list (
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    friendship_status varchar(12),
    UNIQUE (user_id, friend_id)
);

CREATE TABLE genre_film (
    film_id INTEGER REFERENCES films(film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre_list(genre_id) ON DELETE CASCADE,
    UNIQUE (film_id, genre_id)
);

CREATE TABLE films_liked_list (
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films(film_id) ON DELETE CASCADE,
    UNIQUE (user_id, film_id)
);


